version: "3.4"

services:
  main:
    build: .
    restart: always
    environment:
      - DISCORD_TOKEN=
      - DISCORD_CHANNEL=
      - TWITTER_CONSUMER_KEY=
      - TWITTER_CONSUMER_SECRET=
      - TWITTER_TOKEN_KEY=
      - TWITTER_TOKEN_SECRET=